const app=document.querySelector('#app');
const API=(window.MARIAGE_CONFIG?.apiUrl||'').replace(/\/$/,'');
const LOGO="data:image/webp;base64,UklGRqIUAABXRUJQVlA4WAoAAAAQAAAA/wEA/wEASUNDUMgBAAAAAAHIAAAAAAQwAABtbnRyUkdCIFhZWiAH5QAHAAQAAAAVACBhY3NwQVBQTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9tYAAQAAAADTLQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAApkZXNjAAAA/AAAAGRjcHJ0AAABYAAAADZ3dHB0AAABmAAAABRyWFlaAAABrAAAABRnWFlaAAABwAAAABRiWFlaAAAB1AAAABRyVFJDAAAB6AAAACBnVFJDAAAB6AAAACBiVFJDAAAB6AAAACBjcHJ0AAACCAAAADxtbHVjAAAAAAAAAAEAAAAMZW5VUwAAAEgAAAAcAHMAUgBHAEIAIABiAHUAaQBsAHQALQBpAG4AAAAAQABjAHByAHQAAAAAAHhtbHVjAAAAAAAAAAEAAAAMZW5VUwAAABoAAAAcAFAAdQBiAGwAaQBjACAARABvAG0AYQBpAG4AAAAAAFhZWiAAAAAAAAD21gABAAAAANMtWFlaIAAAAAAAAGGXAAC4PQAAClhYWVogAAAAAAAAJKAAAA+EAAC2z1hZWiAAAAAAAAA9GgAAsT0AABbKcGFyYQAAAAAAAwAAAAJmZgAA8qcAAA1ZAAAT0AAACltzZjMyAAAAAAABDEoAAL9j///2OwAAA5AAAMtlAAAgbQ==";
const schedule=[
{time:'15h15',title:'Accueil des invités',address:'Pl. Hector Berlioz, 38640 Claix',maps:'https://www.google.com/maps/search/?api=1&query=Place+Hector+Berlioz+38640+Claix'},
{time:'15h30',title:'Cérémonie civile',address:'Pl. Hector Berlioz, 38640 Claix',maps:'https://www.google.com/maps/search/?api=1&query=Place+Hector+Berlioz+38640+Claix'},
{time:'16h30',title:'Cérémonie religieuse',address:"Église Saint-Étienne, 37 avenue du Maquis de l’Oisans, 38800 Le Pont-de-Claix",maps:'https://www.google.com/maps/search/?api=1&query=Eglise+Saint+Etienne+37+avenue+du+Maquis+de+l+Oisans+38800+Le+Pont+de+Claix'},
{time:'18h00',title:"Vin d’honneur, dîner et soirée dansante",address:'2 Rue Émile Chavant, 38320 Bresson',maps:'https://www.google.com/maps/search/?api=1&query=2+Rue+Emile+Chavant+38320+Bresson'}
];
let state={user:JSON.parse(localStorage.getItem('wedding-user')||'null'),token:localStorage.getItem('wedding-token')||'',tab:'home',table:null,tableLocked:true,online:false,adminView:localStorage.getItem('wedding-admin-view')!=='guest',photos:[],stories:[],lastStoryId:localStorage.getItem('last-story-id')||''};
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLowerCase();
async function api(path,options={}){if(!API)throw new Error('Service temporairement indisponible.');const headers={...(options.headers||{})};if(!(options.body instanceof FormData))headers['Content-Type']='application/json';if(state.token)headers.Authorization=`Bearer ${state.token}`;const r=await fetch(`${API}${path}`,{...options,headers,cache:'no-store'});const type=r.headers.get('content-type')||'';const data=type.includes('application/json')?await r.json().catch(()=>({})):await r.blob();if(!r.ok){const e=new Error(data?.error||'Une erreur est survenue.');e.status=r.status;throw e}return data}
async function checkGateway(){try{await api('/api/health');state.online=true}catch{state.online=false}}
async function login(e){e.preventDefault();const fd=new FormData(e.target),error=document.querySelector('#error');error.textContent='';try{const data=await api('/api/login',{method:'POST',body:JSON.stringify({name:String(fd.get('name')||''),password:String(fd.get('password')||'')})});state.user=data.user;state.token=data.token;localStorage.setItem('wedding-user',JSON.stringify(data.user));localStorage.setItem('wedding-token',data.token);state.adminView=data.user.role==='superadmin';state.tab='home';await refreshData();render()}catch(err){error.textContent=err.message}}
function logout(){localStorage.clear();state.user=null;state.token='';state.tab='home';render()}
function toggleAdminView(){state.adminView=!state.adminView;localStorage.setItem('wedding-admin-view',state.adminView?'admin':'guest');refreshData().then(render)}
function loginView(){app.innerHTML=`<main class="shell login-shell"><section class="hero"><div class="date">29 août 2026</div><h1>Mariage d’Alexandra & Lucas</h1><p>Bienvenue dans notre application de mariage.</p></section><section class="card login-card"><form id="login"><label>Votre prénom</label><input class="field" name="name" autocomplete="given-name" required placeholder="Votre prénom"><div id="password-wrap"></div><p id="error" class="error"></p><button class="btn">Entrer</button></form>${!state.online?'<p class="soft-alert">Le service est momentanément indisponible. Réessayez dans quelques instants.</p>':''}</section></main>`;const input=app.querySelector('[name=name]');input.addEventListener('input',()=>{const secured=['alexandra','lucas','dj'].includes(norm(input.value));document.querySelector('#password-wrap').innerHTML=secured?'<label>Mot de passe</label><input class="field" name="password" type="password" required placeholder="Mot de passe">':''});app.querySelector('#login').addEventListener('submit',login)}
function homeView(){return `<section class="brand-card"><h2>Alexandra & Lucas</h2><p>Nous sommes heureux de partager cette journée avec vous.</p></section><section class="card"><div class="section-title">Le programme</div><div class="timeline">${schedule.map(x=>`<article class="event"><div class="time">${x.time}</div><div><h3>${x.title}</h3><p>${x.address}</p><a class="map-link" href="${x.maps}" target="_blank" rel="noopener">Ouvrir dans Maps</a></div></article>`).join('')}</div></section>`}
async function loadTable(){try{state.table=await api('/api/table');state.tableLocked=false}catch(err){if(err.status===423){state.tableLocked=true;state.table=null}else if(err.status===401)logout()}render()}
function tableView(){if(state.tableLocked)return `<section class="card locked"><span class="gold-icon">✦</span><h2>Votre table sera dévoilée</h2><p class="big-date">29 août à 18h00</p></section>`;if(state.user.role==='dj')return `<section class="card locked"><h2>Compte DJ</h2><p>Vous n’êtes associé à aucune table.</p></section>`;return `<section class="card"><div class="section-title">Votre table</div><div class="table-name">${state.table?.table||''}</div><div class="people">${(state.table?.guests||[]).map(n=>`<span>${n}</span>`).join('')}</div></section>`}
function photoCard(item){return `<figure class="media-card"><img src="${API}${item.url}&token=${encodeURIComponent(state.token)}" loading="lazy"><figcaption><strong>${item.owner}</strong><span>${new Date(item.createdAt).toLocaleString('fr-FR')}</span>${item.comment?`<p>${item.comment}</p>`:''}</figcaption></figure>`}
function photosView(){const title=state.user.role==='superadmin'&&state.adminView?'Toutes les photos':'Vos photos';return `<section class="card upload-card"><div class="section-title">Partagez vos souvenirs</div><p>Ajoutez les photos que vous souhaitez conserver de cette belle journée.</p><form id="photo-form" class="upload-form"><label class="upload-button">＋ Choisir des photos<input type="file" name="photos" accept="image/*" multiple hidden></label><button class="btn" type="submit">Déposer les photos</button><p id="photo-status" class="small"></p></form></section><section class="card"><div class="section-title">${title}</div><div class="gallery">${state.photos.length?state.photos.map(photoCard).join(''):'<p class="empty">Aucune photo pour le moment.</p>'}</div></section>`}
function storiesView(){return `<section class="card upload-card"><div class="section-title">Publier une story</div><p>Partagez un instant avec tous les invités.</p><form id="story-form" class="upload-form"><label class="upload-button">✦ Prendre ou choisir une photo<input type="file" name="photo" accept="image/*" capture="environment" required hidden></label><input class="field" name="comment" maxlength="180" placeholder="Ajouter un petit mot…"><button class="btn">Publier la story</button><p id="story-status" class="small"></p></form></section><section class="card"><div class="section-title">Stories du mariage</div><div class="stories-grid">${state.stories.length?state.stories.map(photoCard).join(''):'<p class="empty">Soyez le premier à publier une story.</p>'}</div></section>`}
function gameView(){const admin=['superadmin','dj'].includes(state.user.role)&&state.adminView;return `${admin?'<section class="card"><div class="section-title">Commandes du jeu</div><div class="admin-grid"><button class="btn">Lancer le jeu</button><button class="btn secondary">Question suivante</button></div></section>':''}<section class="card locked"><span class="gold-icon">♢</span><h2>Le jeu des mariés</h2><p>Le jeu apparaîtra ici lorsque le DJ le lancera.</p></section>`}
function profileView(){return `<section class="card profile"><h2>${state.user.name}</h2><p>${state.user.role==='superadmin'?'Super administrateur':state.user.role==='dj'?'DJ':'Invité'}</p><div class="stats"><div><strong>${state.photos.length}</strong><span>Photos visibles</span></div><div><strong>${state.stories.length}</strong><span>Stories</span></div></div><button class="btn secondary" id="logout">Se déconnecter</button></section>`}
async function uploadMany(form,kind){const input=form.querySelector('input[type=file]'),files=[...input.files],status=form.querySelector('.small');if(!files.length){status.textContent='Sélectionnez au moins une photo.';return}status.textContent='Envoi en cours…';try{for(const file of files){const fd=new FormData();fd.append('photo',file);if(kind==='story')fd.append('comment',form.comment?.value||'');await api(kind==='story'?'/api/stories':'/api/photos',{method:'POST',body:fd})}status.textContent='Publication réussie.';await refreshData();render()}catch(e){status.textContent=e.message}}
async function refreshData(){if(!state.user)return;try{const scope=state.user.role==='superadmin'&&state.adminView?'all':'mine';state.photos=await api(`/api/photos?scope=${scope}`);const previous=state.stories[0]?.id||state.lastStoryId;state.stories=await api('/api/stories');if(state.stories[0]&&previous&&state.stories[0].id!==previous&&state.stories[0].owner!==state.user.name)notifyStory(state.stories[0]);if(state.stories[0]){state.lastStoryId=state.stories[0].id;localStorage.setItem('last-story-id',state.lastStoryId)}}catch(e){}}
function notifyStory(item){if('Notification'in window&&Notification.permission==='granted')new Notification(`Nouvelle story de ${item.owner}`,{body:item.comment||'Un nouveau souvenir vient d’être partagé.'});else{const n=document.createElement('div');n.className='toast';n.textContent=`Nouvelle story de ${item.owner}`;document.body.appendChild(n);setTimeout(()=>n.remove(),3500)}}
function shell(){const superToggle=state.user.role==='superadmin'?`<button class="mode-toggle" id="mode-toggle">${state.adminView?'Vue invité':'Vue Super Admin'}</button>`:'';const content={home:homeView(),table:tableView(),photos:photosView(),live:storiesView(),game:gameView(),profile:profileView()}[state.tab];app.innerHTML=`<main class="shell"><header class="topbar"><div><span>Bienvenue</span><strong>${state.user.name}</strong></div>${superToggle}</header>${content}</main><nav class="nav">${[['home','⌂','Accueil'],['table','◇','Table'],['photos','□','Photos'],['live','✦','Stories'],['game','♢','Jeu'],['profile','○','Profil']].map(([id,icon,label])=>`<button data-tab="${id}" class="${state.tab===id?'active':''}"><b>${icon}</b><span>${label}</span></button>`).join('')}</nav>`;app.querySelectorAll('[data-tab]').forEach(b=>b.onclick=async()=>{state.tab=b.dataset.tab;if(state.tab==='table')await loadTable();else{await refreshData();render()}});app.querySelector('#mode-toggle')?.addEventListener('click',toggleAdminView);app.querySelector('#logout')?.addEventListener('click',logout);app.querySelector('#photo-form')?.addEventListener('submit',e=>{e.preventDefault();uploadMany(e.currentTarget,'photo')});app.querySelector('#story-form')?.addEventListener('submit',e=>{e.preventDefault();if('Notification'in window&&Notification.permission==='default')Notification.requestPermission();uploadMany(e.currentTarget,'story')})}
function render(){state.user?shell():loginView()}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
checkGateway().then(refreshData).finally(()=>{render();setInterval(()=>state.user&&refreshData(),15000)});
