const app=document.querySelector('#app');
const API=(window.MARIAGE_CONFIG?.apiUrl||'').replace(/\/$/,'');
const schedule=[['13:30','Accueil des invités','Mairie de Claix'],['14:00','Cérémonie civile','Mairie de Claix'],['À préciser','Cérémonie religieuse','Église Saint-Étienne'],['18:00','Découverte du plan de table','Lieu de réception'],['Soirée','Dîner, jeu et soirée dansante','Lieu de réception']];
let state={user:JSON.parse(localStorage.getItem('wedding-user')||'null'),token:localStorage.getItem('wedding-token')||'',tab:'home',table:null,tableLocked:true,online:false};
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLowerCase();
async function api(path,options={}){if(!API)throw new Error('Passerelle non configurée.');const headers={'Content-Type':'application/json',...(options.headers||{})};if(state.token)headers.Authorization=`Bearer ${state.token}`;const r=await fetch(`${API}${path}`,{...options,headers,cache:'no-store'});const data=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(data.error||'Erreur de la passerelle.');e.status=r.status;e.data=data;throw e}return data}
async function checkGateway(){try{await api('/api/health');state.online=true}catch{state.online=false}}
async function login(e){e.preventDefault();const fd=new FormData(e.target),error=document.querySelector('#error');error.textContent='';try{const data=await api('/api/login',{method:'POST',body:JSON.stringify({name:String(fd.get('name')||''),password:String(fd.get('password')||'')})});state.user=data.user;state.token=data.token;localStorage.setItem('wedding-user',JSON.stringify(data.user));localStorage.setItem('wedding-token',data.token);state.tab='home';render()}catch(err){error.textContent=err.message}}
function logout(){localStorage.removeItem('wedding-user');localStorage.removeItem('wedding-token');state.user=null;state.token='';state.tab='home';render()}
function loginView(){app.innerHTML=`<main class="shell"><section class="hero"><div class="eyebrow">29 août 2026</div><h1>Alexandra & Lucas</h1><p class="subtitle">Bienvenue dans l’application privée de notre mariage.</p></section><section class="card"><form id="login"><label>Votre prénom</label><input class="field" name="name" autocomplete="given-name" required placeholder="Ex. Kevin"><div id="password-wrap"></div><p id="error" class="error"></p><button class="btn">Entrer</button></form><p class="small">Alexandra, Lucas et le DJ doivent saisir leur mot de passe.</p>${!state.online?'<p class="error">La passerelle est actuellement indisponible.</p>':''}</section></main>`;const input=app.querySelector('[name=name]');input.addEventListener('input',()=>{const secured=['alexandra','lucas','dj'].includes(norm(input.value));document.querySelector('#password-wrap').innerHTML=secured?'<label>Mot de passe</label><input class="field" name="password" type="password" required placeholder="Mot de passe">':''});app.querySelector('#login').addEventListener('submit',login)}
function homeView(){return `<section class="card"><div class="eyebrow">Notre journée</div><div class="timeline">${schedule.map(x=>`<div class="event"><div class="time">${x[0]}</div><div><strong>${x[1]}</strong><div class="small">${x[2]}</div></div></div>`).join('')}</div></section>`}
async function loadTable(){try{const data=await api('/api/table');state.table=data;state.tableLocked=false}catch(err){if(err.status===423){state.tableLocked=true;state.table=null}else if(err.status===401){logout()}}render()}
function tableView(){if(state.tableLocked)return `<section class="card locked"><div class="eyebrow">Encore un peu de patience</div><h2>Le plan de table sera dévoilé</h2><p class="table-name">29 août · 18h00</p><p class="small">Le déverrouillage dépend uniquement de l’heure de la passerelle.</p></section>`;if(state.user.role==='dj')return `<section class="card locked"><h2>Compte DJ</h2><p>Le DJ n’est associé à aucune table.</p></section>`;if(!state.table)return `<section class="card"><p>Chargement du plan de table…</p></section>`;return `<section class="card"><div class="eyebrow">Votre table</div><div class="table-name">${state.table.table}</div><div class="people">${state.table.guests.map(n=>`<span class="person">${n}</span>`).join('')}</div></section>`}
function placeholder(title,text){return `<section class="card module-placeholder"><div class="eyebrow">V1</div><h2>${title}</h2><p class="subtitle">${text}</p></section>`}
function adminPanel(){if(!['superadmin','dj'].includes(state.user.role))return '';return `<section class="card"><div class="eyebrow">${state.user.role==='dj'?'Interface DJ':'Super administration'}</div><h2>Commandes du jeu</h2><div class="admin-grid"><button class="btn">Lancer le jeu</button><button class="btn secondary">Question suivante</button></div><p class="small">La synchronisation complète du jeu sera ajoutée dans la prochaine version.</p></section>`}
function shell(){const content={home:homeView(),table:tableView(),photos:placeholder('Mes photos','Retrouvez ici uniquement les photos que vous avez envoyées au NAS.'),live:placeholder('Live','Prenez une photo, ajoutez un commentaire et publiez-la volontairement dans le fil partagé.'),game:adminPanel()+placeholder('Jeu des mariés','Le jeu s’ouvrira automatiquement quand le DJ le lancera.')}[state.tab];app.innerHTML=`<main class="shell"><header class="topbar"><div><div class="small">Bienvenue</div><div class="welcome">${state.user.name}</div></div><div><span class="pill">${state.user.role==='superadmin'?'Super Admin':state.user.role==='dj'?'DJ':state.user.table||'Invité'}</span></div></header>${content}<button class="btn secondary" id="logout">Se déconnecter</button></main><nav class="nav">${[['home','Accueil'],['table','Table'],['photos','Photos'],['live','Live'],['game','Jeu']].map(([id,label])=>`<button data-tab="${id}" class="${state.tab===id?'active':''}">${label}</button>`).join('')}</nav>`;app.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;if(state.tab==='table')loadTable();else render()});app.querySelector('#logout').onclick=logout}
function render(){state.user?shell():loginView()}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
checkGateway().finally(()=>{render();if(state.user&&state.tab==='table')loadTable()});
