(() => {
  const previousRefresh=refresh, previousHomeView=homeView, previousGameView=gameView, previousProfileView=profileView, previousShell=shell;
  state.events={serverTime:new Date().toISOString(),gates:{pair:false,team:false,tableGames:false},pair:null,team:null,pairs:[],teams:[],guests:[]};
  let clockOffset=0,clockTimer=null,filmTimer=null;
  const icons={
    home:'<svg viewBox="0 0 24 24"><path d="M3 11.5 12 4l9 7.5M5.5 10v10h13V10M9.5 20v-6h5v6"/></svg>',
    table:'<svg viewBox="0 0 24 24"><ellipse cx="12" cy="9" rx="7" ry="4"/><path d="M12 13v7M7.5 12l-2 8M16.5 12l2 8"/></svg>',
    photos:'<svg viewBox="0 0 24 24"><rect x="3" y="6" width="18" height="14" rx="2"/><path d="m8 6 1.5-2h5L16 6"/><circle cx="12" cy="13" r="4"/></svg>',
    live:'<svg viewBox="0 0 24 24"><rect x="4" y="3" width="16" height="18" rx="4"/><circle cx="12" cy="12" r="4"/><circle cx="17" cy="7" r="1"/></svg>',
    game:'<svg viewBox="0 0 24 24"><rect x="3" y="7" width="18" height="11" rx="4"/><path d="M8 10v5M5.5 12.5h5"/><circle cx="16" cy="11" r="1"/><circle cx="18" cy="14" r="1"/></svg>',
    profile:'<svg viewBox="0 0 24 24"><circle cx="12" cy="8" r="4"/><path d="M4.5 21a7.5 7.5 0 0 1 15 0"/></svg>'
  };
  async function loadEvents(){if(!state.user)return;state.events=await api('/api/v26/events').catch(()=>state.events);clockOffset=new Date(state.events.serverTime).getTime()-Date.now()}
  refresh=async function(){await previousRefresh();await loadEvents()};
  const now=()=>new Date(Date.now()+clockOffset);
  const at=value=>new Date(value);
  const guestOptions=(selected='')=>`<option value="" ${!selected?'selected':''}>Choisir une personne</option>`+(state.events.guests||[]).map(name=>`<option value="${esc(name)}" ${name===selected?'selected':''}>${esc(name)}</option>`).join('');
  const pairOptions=(selected='')=>`<option value="" ${!selected?'selected':''}>Choisir un binôme</option>`+(state.events.pairs||[]).map(pair=>`<option value="${esc(pair.name)}" ${pair.name===selected?'selected':''}>${esc(pair.name)}</option>`).join('');

  function automaticMoment(){
    const current=now(),day=at('2026-08-29T00:00:00+02:00'),eight=at('2026-08-29T08:00:00+02:00'),fifteen=at('2026-08-29T15:00:00+02:00'),church=at('2026-08-29T15:45:00+02:00'),churchEnd=at('2026-08-29T17:30:00+02:00'),dinner=at('2026-08-29T18:00:00+02:00'),finish=at('2026-08-30T02:00:00+02:00');
    if(current<day){const days=Math.ceil((day-current)/86400000);return {type:'countdown',eyebrow:'Avant notre mariage',title:`J-${days}`,sub:'29 août 2026'}}
    if(current<eight)return {type:'countdown',eyebrow:'C’est aujourd’hui',title:'Bienvenue',sub:'Rendez-vous à partir de 15h00'};
    if(current<fifteen){const mins=Math.max(0,Math.ceil((fifteen-current)/60000)),h=Math.floor(mins/60),m=mins%60;return {type:'countdown',eyebrow:'Début de la journée dans',title:`${h} h ${String(m).padStart(2,'0')}`,sub:'Accueil à 15h00'}}
    if(current<church)return {type:'stage',number:1,title:'Accueil et mairie'};
    if(current<churchEnd)return {type:'stage',number:2,title:'Église'};
    if(current<dinner)return {type:'stage',number:3,title:'Trajet vers le dîner'};
    if(current<finish)return {type:'stage',number:4,title:'Dîner et soirée'};
    return {type:'finished',title:'Mariage terminé',sub:'Merci d’avoir partagé cette journée inoubliable avec nous. Alexandra & Lucas'};
  }
  homeView=function(){
    const moment=automaticMoment(),announcements=(state.v24.announcements||[]).map(a=>`<article class="announcement"><span>En direct</span><p>${esc(a.text)}</p><small>${new Date(a.createdAt).toLocaleString('fr-FR')}</small></article>`).join('');
    const momentHtml=moment.type==='stage'?`<div class="auto-stage"><b>${moment.number}</b><strong>${moment.title}</strong></div>`:moment.type==='finished'?`<div class="auto-finished"><strong>${moment.title}</strong><p>${moment.sub}</p></div>`:`<div class="auto-countdown"><span>${moment.eyebrow}</span><strong>${moment.title}</strong><small>${moment.sub}</small></div>`;
    return `<section class="brand-card"><img class="home-logo official-logo" src="${LOGO}" alt="Logo officiel"><h2>Alexandra & Lucas</h2><p>Nous sommes heureux de partager cette journée avec vous.</p></section>${announcements?`<section class="card"><div class="section-title">Annonces</div>${announcements}</section>`:''}<section class="card"><div class="section-title">En ce moment</div>${momentHtml}</section><section class="card"><div class="section-title">Informations pratiques</div>${schedule.slice(0,4).map(item=>`<article class="practical"><div><strong>${esc(item.title)}</strong><p>${esc(item.time)} — ${esc(item.address)}</p></div><a href="${item.maps}" target="_blank">GPS</a></article>`).join('')}</section>`;
  };

  function pairSection(){const gate=state.events.gates?.pair,pair=state.events.pair,partner=pair?.members?.find(x=>x!==state.user.name);if(!gate)return `<section class="card event-locked"><div class="section-title">Avant la mairie</div><h2>Retrouvez votre binôme</h2><b>Accessible à partir de 15h00</b></section>`;if(!pair)return `<section class="card"><div class="section-title">Avant la mairie</div><h2>Retrouvez votre binôme</h2><p class="soft-alert">Aucun binôme ne vous a encore été attribué.</p></section>`;return `<section class="card"><div class="section-title">Avant la mairie</div><h2>${esc(pair.name)}</h2><div class="pair-box ${pair.validated?'validated':''}"><span>Retrouvez</span><strong>${esc(partner)}</strong><p>${pair.validated?'Défi validé pour vous deux !':'Prenez une photo ensemble pour valider le défi.'}</p>${pair.photo?`<img src="${API}${pair.photo}&token=${encodeURIComponent(state.token)}">`:''}${!pair.validated?`<form id="pair-proof"><label class="upload-button">Prendre votre photo<input name="media" type="file" accept="image/*" capture="environment" required hidden></label><button class="btn">Valider pour ${esc(pair.name)}</button></form>`:''}</div></section>`}
  function teamSection(){const gate=state.events.gates?.team,team=state.events.team;if(!gate)return `<section class="card event-locked"><div class="section-title">Entre la mairie et l’église</div><h2>Retrouvez l’autre binôme</h2><b>Accessible à partir de 15h45</b></section>`;if(!team)return `<section class="card"><div class="section-title">Entre la mairie et l’église</div><h2>Équipe de quatre</h2><p class="soft-alert">Aucune équipe ne vous a encore été attribuée.</p></section>`;return `<section class="card"><div class="section-title">Entre la mairie et l’église</div><h2>${esc(team.name)}</h2><p>Les binômes <b>${esc(team.pairs?.[0])}</b> et <b>${esc(team.pairs?.[1])}</b> doivent se retrouver.</p><div class="people">${(team.members||[]).map(x=>`<span>${esc(x)}</span>`).join('')}</div><form id="assigned-team-proof"><select class="field" name="text"><option>Trouvez un point commun surprenant</option><option>Formez les lettres A et L</option><option>Reproduisez une pochette d’album</option><option>Inventez un nom et une devise</option></select><label class="upload-button">Photo de l’équipe<input name="media" type="file" accept="image/*" capture="environment" required hidden></label><button class="btn">Valider pour les quatre participants</button></form></section>`}
  function tableGamesSection(){const info=window.MARIAGE_V24?.gameInfo||{},gate=state.events.gates?.tableGames;return `<section class="card"><div class="section-title">Les jeux des quatre tables</div>${!gate?'<p class="games-time-lock">🔒 Accessibles à partir de 18h00, en même temps que la révélation des tables.</p>':''}<div class="games-grid">${Object.entries(info).map(([id,g])=>{const unlocked=state.v24.progress?.unlocked?.includes(id),done=state.v24.progress?.completed?.includes(id),active=gate&&unlocked;return `<article class="game-card ${active?'unlocked':'locked-game'}"><div class="game-icon">${g.icon}</div><div class="game-copy"><small>${g.name}</small><h3>${g.title}</h3><p>${gate?(unlocked?g.description:'Scannez le QR code de cette table pour déverrouiller le jeu.'):'Disponible à 18h00'}</p></div><button class="mini-btn ${done?'success':''}" ${active?`data-open-game="${id}"`:'disabled'}>${done?'Terminé ✓':active?'Jouer':'🔒'}</button></article>`}).join('')}</div></section>`}
  gameView=function(){let html=previousGameView();html=html.replace(/<section class="card"><div class="section-title">Avant la mairie<\/div>.*?<\/section>/,pairSection());html=html.replace(/<section class="card"><div class="section-title">Entre la mairie et l’église<\/div>.*?<\/section>/,teamSection());html=html.replace(/<section class="card"><div class="section-title">Les jeux des quatre tables<\/div>.*?<\/section>/,tableGamesSection());return html};

  function manualGroups(){if(!(state.user.role==='superadmin'&&state.adminView))return '';return `<section class="card manual-groups"><div class="section-title">Binômes manuels</div><p>Donnez un nom à chaque binôme et choisissez exactement deux personnes.</p><div id="pair-editor">${(state.events.pairs||[]).map(pairRow).join('')}</div><button class="btn secondary" id="add-pair">＋ Ajouter un binôme</button><button class="btn" id="save-pairs">Enregistrer les binômes</button></section><section class="card manual-groups"><div class="section-title">Équipes de quatre</div><p>Associez deux binômes qui devront se retrouver entre la mairie et l’église.</p><div id="team-editor">${(state.events.teams||[]).map(teamRow).join('')}</div><button class="btn secondary" id="add-team">＋ Ajouter une équipe</button><button class="btn" id="save-teams">Enregistrer les équipes</button></section>`}
  function pairRow(pair={name:'',members:['','']}){return `<div class="group-row pair-row"><input class="field pair-name" placeholder="Nom du binôme" value="${esc(pair.name)}"><select class="field pair-member">${guestOptions(pair.members?.[0])}</select><select class="field pair-member">${guestOptions(pair.members?.[1])}</select><button class="remove-group" type="button">×</button></div>`}
  function teamRow(team={name:'',pairs:['','']}){return `<div class="group-row team-row"><input class="field team-name" placeholder="Nom de l’équipe (facultatif)" value="${esc(team.name)}"><select class="field team-pair">${pairOptions(team.pairs?.[0])}</select><select class="field team-pair">${pairOptions(team.pairs?.[1])}</select><button class="remove-group" type="button">×</button></div>`}
  function souvenirFilm(){const available=now()>=at('2026-08-30T08:00:00+02:00'),photos=(state.photos||[]).filter(x=>(x.mediaType||'image')==='image').slice(0,8);if(!available)return '';return `<section class="card souvenir-film"><div class="section-title">Votre film souvenir</div><h2>Votre mariage en quelques secondes</h2>${photos.length?`<div class="film-cover"><div>${photos.map((p,i)=>`<img src="${mediaUrl(p)}" data-film-image="${i}" class="${i===0?'active':''}">`).join('')}<p id="film-caption">Votre journée commence ici…</p></div><button class="btn" id="play-film">▶ Voir mon mini-film</button></div>`:'<p>Ajoutez quelques photos pour générer automatiquement votre mini-film souvenir.</p>'}</section>`}
  profileView=function(){
    let html=previousProfileView();
    html=html.replace(/<section class="card"><div class="section-title">Préparation des binômes<\/div>.*?<\/section>/,'');
    if(state.user?.role==='superadmin'&&state.adminView){
      html=html.replace(/<section class="card quiz-editor">.*?<\/section>/,'');
      return `<section class="card admin-console-head"><div class="section-title">Configuration Super Admin</div><h2>Préparation des animations</h2><p>Cette console est réservée à Alexandra et Lucas. Elle est indépendante de la page du DJ.</p></section>${window.MARIAGE_QUIZ_V25?.editor?.()||''}${manualGroups()}<details class="admin-other"><summary>Autres outils Super Admin</summary>${html}</details>`;
    }
    return `${html}${souvenirFilm()}`;
  };

  function participantPicker(title){return `<div class="participant-picker"><label>${title}</label><div class="participant-add"><select class="field person-select"><option value="">Choisir un prénom</option>${guestOptions()}</select><button type="button" class="mini-btn add-person">Ajouter</button></div><div class="selected-people"></div><input type="hidden" name="participants"></div>`}
  function bindParticipantPicker(root){root.querySelectorAll('.participant-picker').forEach(picker=>{const select=picker.querySelector('.person-select'),list=picker.querySelector('.selected-people'),hidden=picker.querySelector('[name=participants]'),people=[];picker.querySelector('.add-person').onclick=()=>{if(!select.value||people.includes(select.value))return;people.push(select.value);draw()};function draw(){hidden.value=people.join('|');list.innerHTML=people.map((name,i)=>`<button type="button" data-remove-person="${i}">${esc(name)} ×</button>`).join('');list.querySelectorAll('button').forEach(b=>b.onclick=()=>{people.splice(Number(b.dataset.removePerson),1);draw()})}})}
  function openChallenge(button){const titles=['Trois générations réunies','Une rencontre entre les deux familles','La plus belle photo de danse','Une photo avec les mariés','Le meilleur selfie de groupe'],title=titles[Number(button.dataset.challenge)];const modal=document.createElement('div');modal.className='game-modal';modal.innerHTML=`<section><button class="modal-close">×</button><h2>${esc(title)}</h2><form><input type="hidden" name="text" value="${esc(title)}">${participantPicker('Personnes présentes sur la photo')}<label class="upload-button">Prendre la photo<input name="media" type="file" accept="image/*" capture="environment" required hidden></label><button class="btn">Valider le défi</button></form></section>`;document.body.appendChild(modal);modal.querySelector('.modal-close').onclick=()=>modal.remove();bindParticipantPicker(modal);modal.querySelector('form').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target),btn=e.target.querySelector('.btn');btn.disabled=true;try{await api('/api/v24/challenge-proof',{method:'POST',body:fd});await refresh();modal.remove();render();toast('Défi photo validé pour les personnes sélectionnées')}catch(error){toast(error.message);btn.disabled=false}}}

  function bindEvents(){
    app.querySelector('#assigned-team-proof')?.addEventListener('submit',async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;try{await api('/api/v26/team-proof',{method:'POST',body:new FormData(e.target)});await refresh();render();toast('Défi validé pour l’équipe de quatre')}catch(error){toast(error.message);button.disabled=false}});
    app.querySelectorAll('[data-challenge]').forEach(button=>button.onclick=()=>openChallenge(button));
    app.querySelector('#add-pair')?.addEventListener('click',()=>{app.querySelector('#pair-editor').insertAdjacentHTML('beforeend',pairRow());bindRemove()});
    app.querySelector('#add-team')?.addEventListener('click',()=>{app.querySelector('#team-editor').insertAdjacentHTML('beforeend',teamRow());bindRemove()});
    app.querySelector('#save-pairs')?.addEventListener('click',async()=>{const pairs=[...app.querySelectorAll('.pair-row')].map(row=>({name:row.querySelector('.pair-name').value,members:[...row.querySelectorAll('.pair-member')].map(x=>x.value)}));try{state.events=await api('/api/v26/pairs',{method:'POST',body:JSON.stringify({pairs})});render();toast('Binômes enregistrés')}catch(e){toast(e.message)}});
    app.querySelector('#save-teams')?.addEventListener('click',async()=>{const teams=[...app.querySelectorAll('.team-row')].map(row=>({name:row.querySelector('.team-name').value,pairs:[...row.querySelectorAll('.team-pair')].map(x=>x.value)}));try{state.events=await api('/api/v26/teams',{method:'POST',body:JSON.stringify({teams})});render();toast('Équipes de quatre enregistrées')}catch(e){toast(e.message)}});
    function bindRemove(){app.querySelectorAll('.remove-group').forEach(b=>b.onclick=()=>b.closest('.group-row').remove())}bindRemove();
    app.querySelector('#play-film')?.addEventListener('click',()=>{clearInterval(filmTimer);const images=[...app.querySelectorAll('[data-film-image]')],captions=['Votre journée commence ici…','Les premiers sourires','Des rencontres inoubliables','Tous réunis pour vous','Des éclats de rire','Une soirée pleine d’émotion','Vos plus beaux souvenirs','Merci pour cette merveilleuse journée'];let index=0;images.forEach((x,i)=>x.classList.toggle('active',i===0));app.querySelector('#film-caption').textContent=captions[0];filmTimer=setInterval(()=>{images[index].classList.remove('active');index=(index+1)%images.length;images[index].classList.add('active');app.querySelector('#film-caption').textContent=captions[index%captions.length];if(index===images.length-1)setTimeout(()=>clearInterval(filmTimer),2300)},2300)});
  }
  function fixIcons(){['home','table','photos','live','game','profile'].forEach(id=>{const target=app.querySelector(`[data-tab="${id}"] .nav-icon`);if(target)target.innerHTML=icons[id]})}
  shell=function(){previousShell();bindEvents();fixIcons();window.MARIAGE_QUIZ_V25?.bind?.();if(state.user?.role==='superadmin'&&state.adminView){const profile=app.querySelector('[data-tab="profile"]');if(profile){profile.querySelector('.nav-label').textContent='Configuration';profile.setAttribute('aria-label','Configuration Super Admin')}}clearInterval(clockTimer);if(state.tab==='home')clockTimer=setInterval(()=>render(),60000)};
  if(state.user)loadEvents().finally(render);
})();
